server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/javtr/dh-especializacion-B1.git/parcial_1
          default-label: main
          search-paths: service-configuration